### ISSUE TITLE
decoding urls sometimes hangs

### ISSUE THREAD

**Issue by casualjim** [scalatra/rl#1]
For this url: http://cdn2.mos.techradar.futurecdn.net//Review%20images/TechRadar/Computing/Components/AMD%20Radeon%20HD%207970/100%%20load-580-90.jpg

on 

https://github.com/backchatio/rl/blob/next/src/main/scala/rl/UrlCodingUtils.scala#L70

There are some urls from http://techradar.com that hang here: https://github.com/backchatio/rl/blob/next/src/main/scala/rl/UrlCodingUtils.scala#L86

http://cdn0.mos.techradar.futurecdn.net//art/tablets/Amazon/Kindle%20Fire%20HD%207/KindleFireHD7LandscapeAngle-900-80.jpg

**Comment by ayush** [comment]
Here are some more which fail:

http://cdn1.mos.techradar.futurecdn.net//art/pc_cases_and_cooling/Thermaltake/Water%202.0%20Performer/stock%20100%-580-90.jpg

http://cdn2.mos.techradar.futurecdn.net//Review%20images/TechRadar/Computing/Components/AMD%20Radeon%20HD%207970/100%%20load-580-90.jpg

http://cdn1.mos.techradar.futurecdn.net//art/pc_cases_and_cooling/Spire/Gemini%20Rev.%202/CPU%20100%-580-90.jpg

http://cdn1.mos.techradar.futurecdn.net//art/pc_cases_and_cooling/Thermaltake/Water%202.0%20Performer/oc%20100%-580-90.jpg

all stuck at

```
    at rl.UrlCodingUtils$class.urlDecode(UrlCodingUtils.scala:70)
    at rl.UrlCodingUtils$.urlDecode(UrlCodingUtils.scala:110)
```
